name: postgresql
replicaCount: 1

image:
  repository: postgres
  tag: "14"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

auth:
  database: "mydb"
  username: "myuser"
  password: "SuperSecret123"  # must match flask-app pgPassword

resources: {}
